repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace

-   repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.13.0
    hooks:
    -   id: markdownlint
